name: Plan Integration Tests
description: Preparing for integration tests.
author: is-devops-team@canonical.com
inputs:
  plan:
    description: operator-workflows plan.
    required: true
  github-token:
    description: github token
    required: true
  check-run-id:
    description: check run id
    required: true
outputs:
  scans:
    description: required scans.
runs:
  using: node20
  main: ../../dist/plan-integration/index.js
