# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Auto-update Charm Libraries
on:
  workflow_call:
    inputs:
      charmcraft-channel:
        description: Charmcraft channel to use for publishing the charm and resources
        type: string
        default: latest/stable
      working-directory:
        type: string
        description: The working directory for jobs
        default: "./"

jobs:
  update-lib:
    permissions:
      pull-requests: write
      contents: write
    name: Check libraries
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Resolve charmcraft.yaml
        id: resolve-charmcraft
        working-directory: ${{ inputs.working-directory }}
        run: |
          if [ -f charmcraft.yaml ] || [ -f charmcraft.yml ]; then
            exit 0
          fi
          candidates=()
          for f in *charmcraft.yaml *charmcraft.yml; do
            [ -f "$f" ] && candidates+=("$f")
          done
          if [ ${#candidates[@]} -eq 0 ]; then
            exit 0
          fi
          echo "Linking charmcraft.yaml to ${candidates[0]}"
          ln -s "${candidates[0]}" charmcraft.yaml
          echo "linked=true" >> "$GITHUB_OUTPUT"
      - name: Check libs
        working-directory: ${{ inputs.working-directory }}
        run: |
          sudo snap install charmcraft --classic --channel ${{ inputs.charmcraft-channel }}
          charmcraft fetch-lib
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
      - name: Remove charmcraft.yaml symlink
        if: always() && steps.resolve-charmcraft.outputs.linked == 'true'
        working-directory: ${{ inputs.working-directory }}
        run: rm -f charmcraft.yaml
      - name: Create pull request
        uses: canonical/create-pull-request@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update charm libraries"
          branch-name: "chore/auto-libs"
          title: Update charm libraries
          body: |
            Automated action to fetch latest version of charm libraries. The branch of this PR
            will be wiped during the next check. Unless you really know what you're doing, you
            most likely don't want to push any commits to this branch.
          upsert: true
          ignore-no-changes: true
