# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Build Rockcraft Cache

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: Image runner for building the images
        default: ubuntu-22.04
      trivy-image-config:
        type: string
        description: Trivy YAML configuration for image testing that is checked in as part of the repo
      working-directory:
        type: string
        description: The working directory for jobs
        default: "./"

jobs:
  build-rockcraft-cache:
    name: Build rock
    uses: ./.github/workflows/build_rocks.yaml
    with:
      owner: ${{ github.repository_owner }}
      registry: ghcr.io
      runs-on: ${{ inputs.runs-on }}
      trivy-image-config: ${{ inputs.trivy-image-config }}
      working-directory: ${{ inputs.working-directory }}
      cache-action: save