# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: Build Charmcraft Cache

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        description: Image runner for building the images
        default: ubuntu-22.04
      working-directory:
        type: string
        description: The working directory for jobs
        default: "./"

jobs:
  build-charmcraft-cache:
    name: Build Charmcraft Cache
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: canonical/setup-lxd@v0.1.1
      - name: Generate charmcraft cache key
        run: |
          WORKING_DIR="${{ inputs.working-directory }}"
          WORKING_DIR=${WORKING_DIR%/}
          CHARM_NAME=$(yq .name ./metadata.yaml)
          CHARMCRAFT_BASE="$(yq -o=j -I=0 '.bases | sort_keys(..)' ./charmcraft.yaml)"
          CHARMCRAFT_BASE=$(printf %s "$CHARMCRAFT_BASE"|jq -sRr @uri)
          CHARMCRAFT_CACHE_KEY_BASE="$WORKING_DIR/charmcraft-cache?name=$CHARM_NAME&bases=$CHARMCRAFT_BASE"
          echo "CHARMCRAFT_CACHE_KEY=$CHARMCRAFT_CACHE_KEY_BASE&date=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo 'CHARMCRAFT_CACHE_ALT_KEYS<<EOF' >> $GITHUB_ENV 
          for d in {1..2}
            do echo "$CHARMCRAFT_CACHE_KEY_BASE&date=$(date -d"-$d days" +%Y-%m-%d)" >> $GITHUB_ENV
          done
          echo 'EOF' >> $GITHUB_ENV
      - name: Build Charm
        run: |
          charmcraft pack
      - name: Generate charmcraft container cache
        run: |
          mkdir -p ~/.charmcraft-cache
          INODE_NUM=$(ls -id . | cut -f 1 -d " ")
          for CONTAINER in $(sudo lxc list --project charmcraft -f table | grep charmcraft | cut -f 2 -d " ")
            do sudo lxc --project charmcraft export $CONTAINER --compression none ~/.charmcraft-cache/$(echo $CONTAINER | sed s/$INODE_NUM/INODE/g).tar 
          done
      - name: Delete charmcraft container cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/caches?key=$(printf %s "${{ env.CHARMCRAFT_CACHE_KEY }}"|jq -sRr @uri) || :
          for key in $(echo "${{ env.CHARMCRAFT_CACHE_ALT_KEYS }}")
            do gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/actions/caches?key=$(printf %s "$key"|jq -sRr @uri) || :
          done
      - name: Save charmcraft container cache
        uses: actions/cache/save@v3.3.1
        with:
          path: ~/.charmcraft-cache/
          key: ${{ env.CHARMCRAFT_CACHE_KEY }}
