# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

# this workflow requires to provide JIRA webhook URL via JIRA_URL GitHub Secret
# read more: https://support.atlassian.com/cloud-automation/docs/jira-automation-triggers/#Automationtriggers-Incomingwebhook
# original code source: https://github.com/beliaev-maksim/github-to-jira-automation

name: Issues to JIRA

on:
  workflow_call:

jobs:
  update:
    name: Update Issue
    runs-on: ubuntu-latest
    steps:
      - name: Create JIRA ticket
        run: |
          echo "This workflow is deprecated and will be removed on 2026/07."
          echo "Consider using https://github.com/canonical/gh-jira-sync-bot"
          exit 1
