name: Load tests

on:
  workflow_call:
    inputs:
      pre-run-script:
        description: Path to the bash script to be run before the integration and load tests
        type: string
      provider:
        description: Actions operator provider as per https://github.com/charmed-kubernetes/actions-operator#usage
        type: string
        default: microk8s
      setup-devstack-swift:
        description: Use setup-devstack-swift action to prepare a swift server for testing.
        type: boolean
        default: false

jobs:
  get-runner-image:
    name: Get runner image
    uses: ./.github/workflows/common/get_runner_image.yaml
  build-images:
    name: Build image
    needs: get-runner-image
    uses: ././.github/workflows/common/build_images.yaml
    with:
      runs-on: ${{ needs.get-runner-image.outputs.runs-on }}
  load_test:
    name: Run Load Tests
    runs-on: ubuntu-22.04
    needs: [get-runner-image, build-images]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
          uses: .github/common/set_up_run_environment
          with:
            images: ${{ needs.build-images.outputs.images }}
            pre-run-script: ${{ inputs.pre-run-script }}
            provider: ${{ inputs.provider }}
            setup-devstack-swift: ${{ inputs.setup-devstack-swift }}
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Pack the charm
        run: charmcraft pack --verbose
      - name: Deploy charm
        run: bash load_tests/deploy-charm.sh
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load_tests/load-test.js
