# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Publish charm

on:
  push:

jobs:
  get-plan:
    name: Get plan
    runs-on: ubuntu-latest
    outputs:
      has-code-changes: ${{ steps.changes.outputs.has-code-changes }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
            fetch-depth: 0
      - name: Find changes
        id: changes
        run: |
          echo ${{ github.event.before }}
          echo ${{ github.event.after }}
          CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.event.after }}")
          CODE_FILE_CHANGES=$(echo "$CHANGED_FILES" | grep -v "\.md$" | wc -l)
          echo "has_code_changes=$([[ $CODE_FILE_CHANGES -eq "0" ]] && echo 'False' || echo 'True')" >> $GITHUB_OUTPUT

