name: Test and notify failure

on:
  inputs:
    integration-test-extra-arguments:
      description: Additional arguments to pass to the integration tests
      type: string
    integration-test-pre-run-script:
      description: Path to the bash script to be run before the integration tests
      type: string
    integration-test-provider:
      description: Actions operator provider for the integration tests as per https://github.com/charmed-kubernetes/actions-operator#usage
      type: string
      default: microk8s
    integration-test-series:
      description: List of series to run the integration tests in JSON format, i.e. '["jammy", "focal"]'. Each element will be passed to tox as --series argument
      type: string
      default: '[""]'
    email-server-address:
      description: Address of email server used for sending email
      type: string
      default: smtp.gmail.com
    email-server-port:
      description: Port of email server used for sending email
      type: int
      default: 465
    email-receiver:
      description: Email address for receiving the failure notification.
      type: string

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/test.yaml
  integration-tests:
    name: Run integration tests
    uses: ./.github/workflows/integration_test.yaml
    with:
      extra-arguments: ${{ inputs.integration-test-extra-arguments }}
      pre-run-script: ${{ inputs.integration-test-pre-run-script }}
      provider: ${{ inputs.integration-test-provider }}
      series: ${{ inputs.integration-test-series }}
    secrets: inherit
  notify-on-failure:
    name: Notify on failure
    needs: [integration-test, tests]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check credential exists
        if: ${{ secrets.EMAIL_USERNAME == null || secrets.EMAIL_PASSWORD == null }}
        run: |
          echo "Missing email username and password as input for this workflow."
          exit 1
      - name: Notify Failure
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ inputs.email-server-address }}
          server_port: ${{ inputs.email-server-port }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: ${{ inputs.email-receiver }}
          subject: "[Scheduled Test] Test in ${{ github.repository }} has failed"
          body: |
            Scheduled test of ${{ github.repository }} has failed.
            Run ID: ${{ github.run_id}}
            Run Number: ${{ github.run_number }}
            Run Attempt: ${{ github.run_attempt}}
            URL: ${{ github.repositoryUrl }}
