# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: Workflow test publish

on:
  workflow_dispatch:

jobs:
  publish:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/publish_charm.yaml
    secrets: inherit
    needs:
      - integration-rock
    with:
      channel: latest/edge
      working-directory: tests/workflows/integration/test-upload-charm/
